[project]
name = ""
version = ""
description = ""
authors = []
dependencies = [
    "onepush",
    "orjson>=3.9.10",
    "loguru>=0.7.2",
    "pydantic>=2.4.2",
    "httpx>=0.25.1",
    "cryptography>=41.0.5",
    "pyyaml>=6.0.1",
    "tenacity>=8.2.3",
    "tzdata>=2023.3",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
